set enc=utf8 fencs=ucs-bom,utf-8,euc-kr
set sw=4 sts=4 ts=8 noai nosi
set nu nowrap nows
set et
set bg=dark
set modeline
set nobackup noswapfile
se bufhidden=unload
se undolevels=5
sy on
autocmd FileType java set sw=4 sts=4 ts=8 et
au BufEnter *.java set ai sw=4 sts=4 ts=8 et
autocmd FileType python set sw=4 sts=4 ts=8 et
au BufEnter *.py set ai sw=4 sts=4 ts=8 et
autocmd FileType yaml set sw=2 sts=2 ts=8 et
au BufEnter *.yml set ai sw=2 sts=2 ts=8 et
